version: '2'
services:
  mattermost-db:
    build: db
    volumes:
      - /opt/mattermost/postgresql/data:/var/lib/postgresql/data
      - /etc/localtime:/etc/localtime:ro
    networks:
      fsc_atlassian_net:
        ipv4_address: 192.168.15.21
    # uncomment the following to enable backup
    #environment:
    #  - AWS_ACCESS_KEY_ID=XXXX
    #  - AWS_SECRET_ACCESS_KEY=XXXX
    #  - WALE_S3_PREFIX=s3://BUCKET_NAME/PATH
    #  - AWS_REGION=us-east-1
  mattermost-app:
    build: app
    links:
      - mattermost-db:db
    volumes:
      - /opt/mattermost/app/config:/mattermost/config:rw
      - /opt/mattermost/app/data:/mattermost/data:rw
      - /etc/localtime:/etc/localtime:ro
    networks:
      fsc_atlassian_net:
        ipv4_address: 192.168.15.22
  mattermost-bridge:
    build: bridge
    ports:
      - "8081:80"
      - "8082:443"
    networks:
      fsc_atlassian_net:
        ipv4_address: 192.168.15.25
  mattermost-web:
    build: web
    ports:
      - "8089:80"
      - "8099:443"
    links:
      - mattermost-app:app
    volumes:
        # This directory must have cert files
      - /opt/mattermost/app/cert:/cert:ro
      - /etc/localtime:/etc/localtime:ro
    environment:
      - MATTERMOST_ENABLE_SSL=true
      - PLATFORM_PORT_80_TCP_PORT=80
    networks:
      fsc_atlassian_net:
        ipv4_address: 192.168.15.23
  
networks:
  fsc_atlassian_net:
    external: true
